######################################################################
#
# File name : tb_flash_led_simulate.do
# Created on: Wed Nov 06 20:35:45 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_flash_led xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_flash_led_wave.do}

view wave
view structure
view signals

do {tb_flash_led.udo}

run 1000ns
