######################################################################
#
# File name : tb_flash_led_compile.do
# Created on: Wed Nov 06 20:35:43 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\IntelModelSim\\modelsim_ase\\win32aloem\\vlib modelsim_lib/work
D:\\IntelModelSim\\modelsim_ase\\win32aloem\\vlib modelsim_lib/msim

D:\\IntelModelSim\\modelsim_ase\\win32aloem\\vlib modelsim_lib/msim/xil_defaultlib

D:\\IntelModelSim\\modelsim_ase\\win32aloem\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\IntelModelSim\\modelsim_ase\\win32aloem\\vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../LED_1.srcs/sources_1/new/flash_led.v" \
"../../../../LED_1.srcs/sim_1/new/tb_flash_led.v" \


# compile glbl module
D:\\IntelModelSim\\modelsim_ase\\win32aloem\\vlog -work xil_defaultlib "glbl.v"

quit -force

