######################################################################
#
# File name : tb_flash_led_wave.do
# Created on: Wed Nov 06 15:51:01 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
